version: '3.8'

services:
  database:
    container_name: ti_database
    image: library/mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
  php:
    container_name: ti
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/integration
    depends_on:
      - database
  nginx:
    container_name: ti_nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - target: 80
        published: 81
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    depends_on:
      - php

networks:
  ti-network:
    driver: bridge
